spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_management
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-circular-references: true